#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: libfreenect_acquisition_shared_library_freenectacquisition openni1_acquisition_shared_library_openni1acquisition openni2_acquisition_shared_library_openni2aquisition opengl_acquisition_shared_library_openglacquisition template_acquisition_shared_library_templateacquisition acquisition_acquisition acquisition_mux_acquisitionmux grabber_grabber grabber_mux_grabbermux

libfreenect_acquisition_shared_library_freenectacquisition: 
	$(MAKE) -C libfreenect_acquisition_shared_library all -f FreenectAcquisition.cbp.mak

openni1_acquisition_shared_library_openni1acquisition: 
	$(MAKE) -C openni1_acquisition_shared_library all -f OpenNI1Acquisition.cbp.mak

openni2_acquisition_shared_library_openni2aquisition: 
	$(MAKE) -C openni2_acquisition_shared_library all -f OpenNI2Aquisition.cbp.mak

opengl_acquisition_shared_library_openglacquisition: 
	$(MAKE) -C opengl_acquisition_shared_library all -f OpenGLAcquisition.cbp.mak

template_acquisition_shared_library_templateacquisition: 
	$(MAKE) -C template_acquisition_shared_library all -f TemplateAcquisition.cbp.mak

acquisition_acquisition: 
	$(MAKE) -C acquisition all -f Acquisition.cbp.mak

acquisition_mux_acquisitionmux: 
	$(MAKE) -C acquisition_mux all -f AcquisitionMux.cbp.mak

grabber_grabber: 
	$(MAKE) -C grabber all -f Grabber.cbp.mak

grabber_mux_grabbermux: 
	$(MAKE) -C grabber_mux all -f GrabberMux.cbp.mak

clean: clean_libfreenect_acquisition_shared_library_freenectacquisition clean_openni1_acquisition_shared_library_openni1acquisition clean_openni2_acquisition_shared_library_openni2aquisition clean_opengl_acquisition_shared_library_openglacquisition clean_template_acquisition_shared_library_templateacquisition clean_acquisition_acquisition clean_acquisition_mux_acquisitionmux clean_grabber_grabber clean_grabber_mux_grabbermux

clean_libfreenect_acquisition_shared_library_freenectacquisition: 
	$(MAKE) -C libfreenect_acquisition_shared_library clean -f FreenectAcquisition.cbp.mak

clean_openni1_acquisition_shared_library_openni1acquisition: 
	$(MAKE) -C openni1_acquisition_shared_library clean -f OpenNI1Acquisition.cbp.mak

clean_openni2_acquisition_shared_library_openni2aquisition: 
	$(MAKE) -C openni2_acquisition_shared_library clean -f OpenNI2Aquisition.cbp.mak

clean_opengl_acquisition_shared_library_openglacquisition: 
	$(MAKE) -C opengl_acquisition_shared_library clean -f OpenGLAcquisition.cbp.mak

clean_template_acquisition_shared_library_templateacquisition: 
	$(MAKE) -C template_acquisition_shared_library clean -f TemplateAcquisition.cbp.mak

clean_acquisition_acquisition: 
	$(MAKE) -C acquisition clean -f Acquisition.cbp.mak

clean_acquisition_mux_acquisitionmux: 
	$(MAKE) -C acquisition_mux clean -f AcquisitionMux.cbp.mak

clean_grabber_grabber: 
	$(MAKE) -C grabber clean -f Grabber.cbp.mak

clean_grabber_mux_grabbermux: 
	$(MAKE) -C grabber_mux clean -f GrabberMux.cbp.mak

.PHONY: clean_libfreenect_acquisition_shared_library_freenectacquisition clean_openni1_acquisition_shared_library_openni1acquisition clean_openni2_acquisition_shared_library_openni2aquisition clean_opengl_acquisition_shared_library_openglacquisition clean_template_acquisition_shared_library_templateacquisition clean_acquisition_acquisition clean_acquisition_mux_acquisitionmux clean_grabber_grabber clean_grabber_mux_grabbermux

