#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: tools_calibration_calibrationlibrary libfreenect_acquisition_shared_library_freenectacquisition openni2_acquisition_shared_library_openni2aquisition openni1_acquisition_shared_library_openni1acquisition opengl_acquisition_shared_library_openglacquisition template_acquisition_shared_library_templateacquisition v4l2_acquisition_shared_library_v4l2acquisition v4l2stereo_acquisition_shared_library_v4l2stereoacquisition acquisition_acquisition acquisition_mux_acquisitionmux acquisitionsegment_acquisitionsegment acquisitionbroadcast_acquisitionbroadcast grabber_mux_grabbermux grabber_segment_grabbersegment grabber_grabber viewer_viewer

tools_calibration_calibrationlibrary: 
	$(MAKE) -C tools/Calibration all -f CalibrationLibrary.cbp.mak

libfreenect_acquisition_shared_library_freenectacquisition: 
	$(MAKE) -C libfreenect_acquisition_shared_library all -f FreenectAcquisition.cbp.mak

openni2_acquisition_shared_library_openni2aquisition: 
	$(MAKE) -C openni2_acquisition_shared_library all -f OpenNI2Aquisition.cbp.mak

openni1_acquisition_shared_library_openni1acquisition: 
	$(MAKE) -C openni1_acquisition_shared_library all -f OpenNI1Acquisition.cbp.mak

opengl_acquisition_shared_library_openglacquisition: 
	$(MAKE) -C opengl_acquisition_shared_library all -f OpenGLAcquisition.cbp.mak

template_acquisition_shared_library_templateacquisition: 
	$(MAKE) -C template_acquisition_shared_library all -f TemplateAcquisition.cbp.mak

v4l2_acquisition_shared_library_v4l2acquisition: 
	$(MAKE) -C v4l2_acquisition_shared_library all -f V4L2Acquisition.cbp.mak

v4l2stereo_acquisition_shared_library_v4l2stereoacquisition: 
	$(MAKE) -C v4l2stereo_acquisition_shared_library all -f V4L2StereoAcquisition.cbp.mak

acquisition_acquisition: 
	$(MAKE) -C acquisition all -f Acquisition.cbp.mak

acquisition_mux_acquisitionmux: 
	$(MAKE) -C acquisition_mux all -f AcquisitionMux.cbp.mak

acquisitionsegment_acquisitionsegment: 
	$(MAKE) -C acquisitionSegment all -f acquisitionSegment.cbp.mak

acquisitionbroadcast_acquisitionbroadcast: 
	$(MAKE) -C acquisitionBroadcast all -f acquisitionBroadcast.cbp.mak

grabber_mux_grabbermux: 
	$(MAKE) -C grabber_mux all -f GrabberMux.cbp.mak

grabber_segment_grabbersegment: 
	$(MAKE) -C grabber_segment all -f GrabberSegment.cbp.mak

grabber_grabber: 
	$(MAKE) -C grabber all -f Grabber.cbp.mak

viewer_viewer: 
	$(MAKE) -C viewer all -f Viewer.cbp.mak

clean: clean_tools_calibration_calibrationlibrary clean_libfreenect_acquisition_shared_library_freenectacquisition clean_openni2_acquisition_shared_library_openni2aquisition clean_openni1_acquisition_shared_library_openni1acquisition clean_opengl_acquisition_shared_library_openglacquisition clean_template_acquisition_shared_library_templateacquisition clean_v4l2_acquisition_shared_library_v4l2acquisition clean_v4l2stereo_acquisition_shared_library_v4l2stereoacquisition clean_acquisition_acquisition clean_acquisition_mux_acquisitionmux clean_acquisitionsegment_acquisitionsegment clean_acquisitionbroadcast_acquisitionbroadcast clean_grabber_mux_grabbermux clean_grabber_segment_grabbersegment clean_grabber_grabber clean_viewer_viewer

clean_tools_calibration_calibrationlibrary: 
	$(MAKE) -C tools/Calibration clean -f CalibrationLibrary.cbp.mak

clean_libfreenect_acquisition_shared_library_freenectacquisition: 
	$(MAKE) -C libfreenect_acquisition_shared_library clean -f FreenectAcquisition.cbp.mak

clean_openni2_acquisition_shared_library_openni2aquisition: 
	$(MAKE) -C openni2_acquisition_shared_library clean -f OpenNI2Aquisition.cbp.mak

clean_openni1_acquisition_shared_library_openni1acquisition: 
	$(MAKE) -C openni1_acquisition_shared_library clean -f OpenNI1Acquisition.cbp.mak

clean_opengl_acquisition_shared_library_openglacquisition: 
	$(MAKE) -C opengl_acquisition_shared_library clean -f OpenGLAcquisition.cbp.mak

clean_template_acquisition_shared_library_templateacquisition: 
	$(MAKE) -C template_acquisition_shared_library clean -f TemplateAcquisition.cbp.mak

clean_v4l2_acquisition_shared_library_v4l2acquisition: 
	$(MAKE) -C v4l2_acquisition_shared_library clean -f V4L2Acquisition.cbp.mak

clean_v4l2stereo_acquisition_shared_library_v4l2stereoacquisition: 
	$(MAKE) -C v4l2stereo_acquisition_shared_library clean -f V4L2StereoAcquisition.cbp.mak

clean_acquisition_acquisition: 
	$(MAKE) -C acquisition clean -f Acquisition.cbp.mak

clean_acquisition_mux_acquisitionmux: 
	$(MAKE) -C acquisition_mux clean -f AcquisitionMux.cbp.mak

clean_acquisitionsegment_acquisitionsegment: 
	$(MAKE) -C acquisitionSegment clean -f acquisitionSegment.cbp.mak

clean_acquisitionbroadcast_acquisitionbroadcast: 
	$(MAKE) -C acquisitionBroadcast clean -f acquisitionBroadcast.cbp.mak

clean_grabber_mux_grabbermux: 
	$(MAKE) -C grabber_mux clean -f GrabberMux.cbp.mak

clean_grabber_segment_grabbersegment: 
	$(MAKE) -C grabber_segment clean -f GrabberSegment.cbp.mak

clean_grabber_grabber: 
	$(MAKE) -C grabber clean -f Grabber.cbp.mak

clean_viewer_viewer: 
	$(MAKE) -C viewer clean -f Viewer.cbp.mak

.PHONY: clean_tools_calibration_calibrationlibrary clean_libfreenect_acquisition_shared_library_freenectacquisition clean_openni2_acquisition_shared_library_openni2aquisition clean_openni1_acquisition_shared_library_openni1acquisition clean_opengl_acquisition_shared_library_openglacquisition clean_template_acquisition_shared_library_templateacquisition clean_v4l2_acquisition_shared_library_v4l2acquisition clean_v4l2stereo_acquisition_shared_library_v4l2stereoacquisition clean_acquisition_acquisition clean_acquisition_mux_acquisitionmux clean_acquisitionsegment_acquisitionsegment clean_acquisitionbroadcast_acquisitionbroadcast clean_grabber_mux_grabbermux clean_grabber_segment_grabbersegment clean_grabber_grabber clean_viewer_viewer

