#Cam_calib_web.py
#Created by Chris Rillahan @02/02/2015
#Written with Python 2.7.2, OpenCV 3.0.0 and NumPy 1.8.0

#Updated by Ammar Qammaz for Python3 @ 19/9/2020

#This program calculates the distortion parameters of a GoPro camera.
#A video must first be taken of a chessboard pattern moved to a variety of positions
#in the field of view with a GoPro.  

import cv2, sys
import numpy as np

#Import Information
filename = 'GOPRO4K.MP4' #GOPR3784.MP4
filename = 'logitech_c920.mkv' #GOPR3784.MP4
filename = 'GX010015.MP4' #GOPR3784.MP4
#Input the number of board images to use for calibration (recommended: ~20)
n_boards = 20
#Input the number of squares on the board (width and height)
board_w = 9
board_h = 6
#Board dimensions (typically in cm)
board_dim = 21
#Image resolution
#image_size = (2704,1520) #2.7 K 
image_size = (2704,1520) #2.7 K 

#Crop mask 
# A value of 0 will crop out all the black pixels.  This will result in a loss of some actual pixels.
# A value of 1 will leave in all the pixels.  This maybe useful if there is some important information 
# at the corners.  Ideally, you will have to tweak this to see what works for you.
crop = 0.5


def save_stereolabs_calib(
    out_path: str,
    width: int,
    height: int,
    intrinsic_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    camera_id: int = 0,
    camera_no: int = 0,
    date: str = "",
    description: str = "",
    scale_unit: float = 1.0,
    comment_camera: str = "GoPro Hero 13 5.3K",
    comment_source: str = "Generated by Cam_calib_web.py"
):
    """
    Save calibration in the Stereolabs/Matlab-load compatible .calib format shown by the user.
    Distortion is written as 5 values: k1, k2, p1, p2, k3 (OpenCV standard order).
    """

    I = np.asarray(intrinsic_matrix, dtype=float).reshape(3, 3)
    D = np.asarray(dist_coeffs, dtype=float).reshape(-1)

    # Ensure at least 5 distortion params in OpenCV order: k1 k2 p1 p2 k3
    if D.size < 5:
        D = np.pad(D, (0, 5 - D.size), mode="constant")
    D = D[:5]

    lines = []
    lines.append(
        f"%Calibration File v 1.0.3 - Matlab Load() compatible, "
        f"https://support.stereolabs.com/hc/en-us/articles/360007497173-What-is-the-calibration-file- "
        f"Scale Unit: {scale_unit}  - {comment_camera} - {comment_source}"
    )
    lines.append(f"%CameraID={camera_id}")
    lines.append(f"%CameraNo={camera_no}")
    lines.append("%Date=" + (date if date is not None else ""))
    lines.append("%Width")
    lines.append(str(int(width)))
    lines.append("%Height")
    lines.append(str(int(height)))
    lines.append("%Description=" + (description if description is not None else ""))

    lines.append("%Intrinsics I[1,1], I[1,2], I[1,3], I[2,1], I[2,2], I[2,3], I[3,1], I[3,2] I[3,3]")
    lines.append("%I")
    # Write I row-major, one value per line (matching your example)
    for r in range(3):
        for c in range(3):
            lines.append(f"{I[r,c]:.8f}")

    lines.append("%Distortion D[1], D[2], D[3], D[4] D[5]")
    lines.append("%D")
    for v in D:
        lines.append(f"{v:.8f}")

    lines.append("%Translation T.X, T.Y, T.Z")
    lines.append("%T")
    lines.append("0")
    lines.append("0")
    lines.append("0")

    lines.append("%Rotation Vector (Rodrigues) R.X, R.Y, R.Z")
    lines.append("%R")
    lines.append("0")
    lines.append("0")
    lines.append("0")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")



def resize_to_fit_screen(img, max_w=1280, max_h=720, only_shrink=True):
    """
    Resize image to fit within (max_w, max_h) while preserving aspect ratio.
    - only_shrink=True: don't upscale small images.
    Returns (resized_img, scale).
    """
    h, w = img.shape[:2]
    scale = min(max_w / float(w), max_h / float(h))

    if only_shrink and scale >= 1.0:
        return img, 1.0

    new_w = max(1, int(round(w * scale)))
    new_h = max(1, int(round(h * scale)))

    interp = cv2.INTER_AREA if scale < 1.0 else cv2.INTER_LINEAR
    return cv2.resize(img, (new_w, new_h), interpolation=interp), scale


#The ImageCollect function requires two input parameters.  Filename is the name of the file
#in which checkerboard images will be collected from.  n_boards is the number of images of
#the checkerboard which are needed.  In the current writing of this function an additional 5
#images will be taken.  This ensures that the processing step has the correct number of images
#and can skip an image if the program has problems.

#This function loads the video file into a data space called video.  It then collects various
#meta-data about the file for later inputs.  The function then enters a loop in which it loops
#through each image, displays the image and waits for a fixed amount of time before displaying
#the next image.  The playback speed can be adjusted in the waitKey command.  During the loop
#checkerboard images can be collected by pressing the spacebar.  Each image will be saved as a
#*.png into the directory which stores this file.  The ESC key will terminate the function.
#The function will end once the correct number of images are collected or the video ends.
#For the processing step, try to collect all the images before the video ends.



def ImageCollect(filename, n_boards):
    #Collect Calibration Images
    print('-----------------------------------------------------------------')
    print('Loading video...')
    print('Press space when you see a clean frame...!')

    #Load the file given to the function
    video = cv2.VideoCapture(filename)
    #Checks to see if a the video was properly imported
    status = video.isOpened()

    if status == True:
        
        #Collect metadata about the file.
        FPS = video.get(cv2.CAP_PROP_FPS)
        FrameDuration = 1/(FPS/1000)+10
        width = video.get(cv2.CAP_PROP_FRAME_WIDTH)
        height = video.get(cv2.CAP_PROP_FRAME_HEIGHT)
        size = (int(width), int(height))
        total_frames = video.get(cv2.CAP_PROP_FRAME_COUNT)

        #Initializes the frame counter and collected_image counter
        current_frame = 0
        collected_images = 0

        #Video loop.  Press spacebar to collect images.  ESC terminates the function.
        while current_frame < total_frames:
            success, image = video.read()
            if (success):

               current_frame = video.get(cv2.CAP_PROP_POS_FRAMES)

               # pick a target display size (change these if you want)
               imageThatFitsOnScreen, _ = resize_to_fit_screen(image, max_w=1600, max_h=900, only_shrink=True)
               cv2.imshow('Video', imageThatFitsOnScreen)


               k = cv2.waitKey(int(FrameDuration)) #You can change the playback speed here
               if collected_images == n_boards: 
                   break
               if k == 32:
                   collected_images += 1
                   cv2.imwrite('Calibration_Image' + str(collected_images) + '.png', image)
                   print(str(collected_images) + ' images collected.')
               if k == 27:
                   break
    
        #Clean up
        video.release()
        cv2.destroyAllWindows()
    else:
        print('Error: Could not load video')
        sys.exit()


#The ImageProcessing function performs the calibration of the camera based on the images
#collected during ImageCollect function.  This function will look for the images in the folder
#which contains this file.  The function inputs are the number of boards which will be used for
#calibration (n_boards), the number of squares on the checkerboard (board_w, board_h) as
#determined by the inside points (i.e. where the black squares touch).  board_dim is the actual
#size of the square, this should be an integer.  It is assumed that the checkerboard squares are
#square.

#This function first initializes a series of variables. Opts will store the true object points
#(i.e. checkerboard points).  Ipts will store the points as determined by the calibration images.
#The function then loops through each image.  Each image is converted to grayscale, and the
#checkerboard corners are located.  If it is successful at finding the correct number of corners
#then the true points and the measured points are stored into opts and ipts, respectively. The
#image with the checkerboard points are then displays.  If the points are not found that image
#is skipped.  Once the desired number of checkerboard points are acquired the calibration
#parameters (intrinsic matrix and distortion coefficients) are calculated.

#The distortion parameter are saved into a numpy file (calibration_data.npz).  The total
#total reprojection error is calculated by comparing the "true" checkerboard points to the
#image measured points once the image is undistorted.  The total reprojection error should be
#close to zero.

#Finally the function will go through the calbration images and display the undistorted image.
    
def ImageProcessing(n_boards, board_w, board_h, board_dim):
    #Initializing variables
    board_n = board_w * board_h
    opts = []
    ipts = []
    npts = np.zeros((n_boards, 1), np.int32)
    intrinsic_matrix = np.zeros((3, 3), np.float32)
    distCoeffs = np.zeros((5, 1), np.float32)
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1)

    # prepare object points based on the actual dimensions of the calibration board
    # like (0,0,0), (25,0,0), (50,0,0) ....,(200,125,0)
    objp = np.zeros((board_h*board_w,3), np.float32)
    objp[:,:2] = np.mgrid[0:(board_w*board_dim):board_dim,0:(board_h*board_dim):board_dim].T.reshape(-1,2)

    #Loop through the images.  Find checkerboard corners and save the data to ipts.
    for i in range(1, n_boards + 1):
    
        #Loading images
        print('Loading... Calibration_Image' + str(i) + '.png') 
        image = cv2.imread('Calibration_Image' + str(i) + '.png')
        if (type(image) is not None): 
           #Converting to grayscale
           grey_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

           #Find chessboard corners
           found, corners = cv2.findChessboardCorners(grey_image, (board_w,board_h),cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_NORMALIZE_IMAGE)
           print (found)

           if found == True:

               #Add the "true" checkerboard corners
               opts.append(objp)

               #Improve the accuracy of the checkerboard corners found in the image and save them to the ipts variable.
               cv2.cornerSubPix(grey_image, corners, (20, 20), (-1, -1), criteria)
               ipts.append(corners)

               #Draw chessboard corners
               cv2.drawChessboardCorners(image, (board_w, board_h), corners, found)
        
               #Show the image with the chessboard corners overlaid.
               imageThatFitsOnScreen, _ = resize_to_fit_screen(image, max_w=1600, max_h=900, only_shrink=True)
               cv2.imshow("Corners", imageThatFitsOnScreen)

               char = cv2.waitKey(20)

    cv2.destroyWindow("Corners") 
    
    print('')
    print('Finished processes images.')

    #Calibrate the camera 
    print('Running Calibrations...')
    print(' ')
    ret, intrinsic_matrix, distCoeff, rvecs, tvecs = cv2.calibrateCamera(opts, ipts, grey_image.shape[::-1],None,None)
 
    # Use the actual calibration image size (important!)
    h, w = grey_image.shape[:2]

    save_stereolabs_calib(
                          out_path="last.calib",
                          width=w,
                          height=h,
                          intrinsic_matrix=intrinsic_matrix,
                          dist_coeffs=distCoeff,
                          camera_id=0,
                          camera_no=0,
                          date="",  # optionally fill
                          description="GoPro Hero 13 calibration (5.3K)"
                         )
    print("Saved Stereolabs-style calibration to last.calib")

    #Save matrices
    print('Intrinsic Matrix: ')
    print(str(intrinsic_matrix))
    print(' ')

    print('fX = ',intrinsic_matrix[0][0]) 
    print('fY = ',intrinsic_matrix[1][1]) 
    print('cX = ',intrinsic_matrix[0][2]) 
    print('cY = ',intrinsic_matrix[1][2]) 
    print(' ')

    print('Distortion Coefficients: ')
    print(str(distCoeff))
    print(' ') 

    #Save data
    print('Saving data file...')
    np.savez('calibration_data', distCoeff=distCoeff, intrinsic_matrix=intrinsic_matrix)
    print('Calibration complete')

    #Calculate the total reprojection error.  The closer to zero the better.
    tot_error = 0
    for i in range(len(opts)):
        imgpoints2, _ = cv2.projectPoints(opts[i], rvecs[i], tvecs[i], intrinsic_matrix, distCoeff)
        error = cv2.norm(ipts[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
        tot_error += error

    print("total reprojection error: ", tot_error/len(opts))

    #Undistort Images

    #Scale the images and create a rectification map.
    image_size  = (w, h)  # (width, height) from grey_image
    newMat, ROI = cv2.getOptimalNewCameraMatrix(intrinsic_matrix, distCoeff, image_size, alpha=crop, centerPrincipalPoint=1)
    mapx, mapy  = cv2.initUndistortRectifyMap(intrinsic_matrix, distCoeff, None, newMat, image_size, m1type=cv2.CV_32FC1)

                                  
    for i in range(1, n_boards + 1):
    
        #Loading images
        print('Loading... Calibration_Image' + str(i) + '.png')
        image = cv2.imread('Calibration_Image' + str(i) + '.png')
        if (type(image) is not None): 

           # undistort
           dst = cv2.remap(image, mapx, mapy, cv2.INTER_LINEAR)


           #dstThatFitsOnScreen = dst
           dstThatFitsOnScreen, _ = resize_to_fit_screen(dst, max_w=1600, max_h=900, only_shrink=True)
           cv2.imshow('Undisorted Image',dstThatFitsOnScreen)

           char = cv2.waitKey(20)

    cv2.destroyAllWindows()


print("Starting camera calibration....")
print("Step 1: Image Collection")
print("We will playback the calibration video.  Press the spacebar to save")
print("calibration images.")
print(" ")
print('We will collect ' + str(n_boards) + ' calibration images.')

#ImageCollect(filename, n_boards)

print(' ')
print('All the calibration images are collected.')
print('------------------------------------------------------------------------')
print('Step 2: Calibration')
print('We will analyze the images take and calibrate the camera.')
print('Press the esc button to close the image windows as they appear.')
print(' ')

ImageProcessing(n_boards, board_w, board_h, board_dim)

