#!/bin/bash
echo "Compiling calibrate.cpp using OpenCV libs"
 g++ -ggdb `pkg-config --cflags opencv` -o calibration "calibrate.cpp" `pkg-config --libs opencv`;
cd cam0
ln -s ../calibration
cd ..

cd cam1
ln -s ../calibration
cd ..
 
echo "Done"
exit 0
