#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fPIC
RESINC = 
LIBDIR = 
LIB = ../tools/Calibration/libCalibrationLibrary.a
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = libacquisitionSegment.a

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -fPIC
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = libacquisitionSegment.a

OBJ_DEBUG = $(OBJDIR_DEBUG)/imageProcessing.o $(OBJDIR_DEBUG)/depthSelector.o $(OBJDIR_DEBUG)/combineRGBAndDepthOutput.o $(OBJDIR_DEBUG)/colorSelector.o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.o $(OBJDIR_DEBUG)/AcquisitionSegment.o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/imageProcessing.o $(OBJDIR_RELEASE)/depthSelector.o $(OBJDIR_RELEASE)/combineRGBAndDepthOutput.o $(OBJDIR_RELEASE)/colorSelector.o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.o $(OBJDIR_RELEASE)/AcquisitionSegment.o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix || mkdir -p $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(AR) rcs $(OUT_DEBUG) $(OBJ_DEBUG)

$(OBJDIR_DEBUG)/imageProcessing.o: imageProcessing.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c imageProcessing.c -o $(OBJDIR_DEBUG)/imageProcessing.o

$(OBJDIR_DEBUG)/depthSelector.o: depthSelector.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c depthSelector.c -o $(OBJDIR_DEBUG)/depthSelector.o

$(OBJDIR_DEBUG)/combineRGBAndDepthOutput.o: combineRGBAndDepthOutput.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c combineRGBAndDepthOutput.c -o $(OBJDIR_DEBUG)/combineRGBAndDepthOutput.o

$(OBJDIR_DEBUG)/colorSelector.o: colorSelector.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c colorSelector.c -o $(OBJDIR_DEBUG)/colorSelector.o

$(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.c -o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.o

$(OBJDIR_DEBUG)/AcquisitionSegment.o: AcquisitionSegment.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c AcquisitionSegment.c -o $(OBJDIR_DEBUG)/AcquisitionSegment.o

$(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.c -o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.o

$(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.c -o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.o

$(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.c -o $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix

before_release: 
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix || mkdir -p $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/imageProcessing.o: imageProcessing.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c imageProcessing.c -o $(OBJDIR_RELEASE)/imageProcessing.o

$(OBJDIR_RELEASE)/depthSelector.o: depthSelector.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c depthSelector.c -o $(OBJDIR_RELEASE)/depthSelector.o

$(OBJDIR_RELEASE)/combineRGBAndDepthOutput.o: combineRGBAndDepthOutput.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c combineRGBAndDepthOutput.c -o $(OBJDIR_RELEASE)/combineRGBAndDepthOutput.o

$(OBJDIR_RELEASE)/colorSelector.o: colorSelector.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c colorSelector.c -o $(OBJDIR_RELEASE)/colorSelector.o

$(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.c -o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix3x3Tools.o

$(OBJDIR_RELEASE)/AcquisitionSegment.o: AcquisitionSegment.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c AcquisitionSegment.c -o $(OBJDIR_RELEASE)/AcquisitionSegment.o

$(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.c -o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/solveLinearSystemGJ.o

$(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.c -o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrixCalculations.o

$(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.o: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.c -o $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix/matrix4x4Tools.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/__/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/AmMatrix

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

