#ifndef SHARED_ACQUISITIONPARAMETERS_H_
    #define SHARED_ACQUISITIONPARAMETERS_H_

    #define FORMAT_QVGA_ID 0
    #define FORMAT_VGA_ID 1
    #define FORMAT_WXGA_ID 2
    #define FORMAT_NHD_ID 3
    #define FORMAT_QVGA_WIDTH 320
    #define FORMAT_QVGA_HEIGHT 240
    #define FORMAT_QVGA_PIXELS 76800
    #define FORMAT_VGA_WIDTH 640
    #define FORMAT_VGA_HEIGHT 480
    #define FORMAT_VGA_PIXELS 307200
    #define FORMAT_WXGA_WIDTH 1280
    #define FORMAT_WXGA_HEIGHT 720
    #define FORMAT_WXGA_PIXELS 921600
    #define FORMAT_NHD_WIDTH 640
    #define FORMAT_NHD_HEIGHT 360
    #define FORMAT_NHD_PIXELS 230400
    #define FILETYPE_NONE 0
    #define FILETYPE_JPG 1
    #define FILETYPE_PNM 2
#endif // SHARED_ACQUISITIONPARAMETERS_H_
